# Generated by Django 6.0.2 on 2026-03-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_room_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='current_electricity_index',
            new_name='current_electricity',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='current_water_index',
            new_name='current_water',
        ),
    ]
