# Generated by Django 6.0.2 on 2026-03-06 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_rename_current_electricity_index_room_current_electricity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='identify',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='CCCD không hợp lệ. Bắt buộc nhập đúng 12 chữ số.', regex='^\\d{12}$')], verbose_name='CCCD'),
        ),
    ]
