# Generated by Django 6.0.2 on 2026-03-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='deposit_rent',
        ),
    ]
