# Generated by Django 6.0.2 on 2026-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_remove_room_deposit_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Trống', 'Trống'), ('Đang thuê', 'Đang thuê'), ('Sửa chữa', 'Sửa chữa')], default='available', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
