# Generated by Django 6.0.2 on 2026-03-06 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='document_file',
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apartment.contract')),
            ],
        ),
    ]
