# Generated by Django 6.0.2 on 2026-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_remove_contract_document_file_contractdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Trống', 'Trống'), ('Đang thuê', 'Đang thuê'), ('Sửa chữa', 'Sửa chữa')], default='Trống', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
