# Generated by Django 6.0.2 on 2026-03-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Trống'), ('rented', 'Đang thuê'), ('maintenance', 'Sửa chữa')], default='available', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
