# Generated by Django 6.0.2 on 2026-03-14 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(error_messages={'invalid': 'Tên phòng chỉ được là số (Lưu ý: Số đầu tiên là số tầng)'}, unique=True, verbose_name='Tên phòng')),
                ('floor', models.IntegerField(error_messages={'invalid': 'Số tầng chỉ được là số'}, verbose_name='Tầng')),
                ('area', models.FloatField(verbose_name='Diện tích (m2)')),
                ('max_occupancy', models.IntegerField(default=1, verbose_name='Số người tối đa')),
                ('base_rent', models.IntegerField(verbose_name='Giá thuê cơ bản')),
                ('air_conditioner', models.BooleanField(default=False, verbose_name='Máy lạnh')),
                ('water_heater', models.BooleanField(default=False, verbose_name='Máy nước nóng')),
                ('refrigerator', models.BooleanField(default=False, verbose_name='Tủ lạnh')),
                ('furniture', models.BooleanField(default=False, verbose_name='Giường/Tủ')),
                ('balcony', models.BooleanField(default=False, verbose_name='Ban công')),
                ('electricity_price', models.IntegerField(verbose_name='Đơn giá Điện')),
                ('water_price', models.IntegerField(verbose_name='Đơn giá Nước')),
                ('trash_price', models.IntegerField(verbose_name='Rác')),
                ('internet_price', models.IntegerField(verbose_name='Internet')),
                ('current_electricity', models.IntegerField(default=0, verbose_name='Chỉ số điện hiện tại')),
                ('current_water', models.IntegerField(default=0, verbose_name='Chỉ số nước hiện tại')),
                ('status', models.CharField(choices=[('Trống', 'Trống'), ('Đang thuê', 'Đang thuê'), ('Sửa chữa', 'Sửa chữa'), ('Đã cọc', 'Đã cọc')], default='Trống', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ. Bắt buộc nhập đúng 10 chữ số.', regex='^\\d{10}$')], verbose_name='Số điện thoại')),
                ('identify', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='CCCD không hợp lệ. Bắt buộc nhập đúng 12 chữ số.', regex='^\\d{12}$')], verbose_name='CCCD')),
                ('start_date', models.DateField(verbose_name='Ngày dọn vào')),
                ('duration', models.IntegerField(default=3, verbose_name='Thời hạn HĐ (Tháng)')),
                ('deposit', models.IntegerField(verbose_name='Tiền cọc giữ chỗ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Người thuê')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='app.room', verbose_name='Phòng')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(verbose_name='Kỳ hóa đơn')),
                ('status', models.CharField(choices=[('draft', 'Lưu nháp'), ('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái')),
                ('base_rent', models.IntegerField(default=0, verbose_name='Tiền thuê phòng')),
                ('electricity_price', models.IntegerField(default=0, verbose_name='Đơn giá điện')),
                ('water_price', models.IntegerField(default=0, verbose_name='Đơn giá nước')),
                ('trash_price', models.IntegerField(default=0, verbose_name='Tiền rác')),
                ('internet_price', models.IntegerField(default=0, verbose_name='Tiền internet')),
                ('old_electricity', models.IntegerField(default=0, verbose_name='Chỉ số điện cũ')),
                ('new_electricity', models.IntegerField(default=0, verbose_name='Chỉ số điện mới')),
                ('old_water', models.IntegerField(default=0, verbose_name='Chỉ số nước cũ')),
                ('new_water', models.IntegerField(default=0, verbose_name='Chỉ số nước mới')),
                ('extra_fee', models.IntegerField(default=0, verbose_name='Phụ phí khác')),
                ('extra_fee_reason', models.TextField(blank=True, null=True, verbose_name='Lý do phụ phí')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Tổng cộng thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.room', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'ordering': ['-billing_month', '-created_at'],
            },
        ),
    ]
